.PHONY: exercise205
exercise205:
	gcc -Wall exercise205/any.c
	./a.out

.PHONY: exercise204
exercise204:
	gcc -Wall exercise204/squeeze.c
	./a.out

.PHONY: exercise203
exercise203:
	gcc -Wall exercise203/htoi.c
	./a.out

.PHONY: exercise202
exercise202:
	gcc -Wall exercise202/nonForLoop.c
	cat exercise202/nonForLoop.c | ./a.out

.PHONY: exercise201
exercise201:
	gcc -Wall exercise201/size.c
	./a.out

.PHONY: main
main:
	gcc -Wall main.c
	cat main.c | ./a.out
