.PHONY: exercise103
exercise103:
	gcc exercise103/tempConvert.c
	./a.out

.PHONY: exercise102
exercise102:
	gcc exercise102/hello.c
	./a.out

.PHONY: exercise101
exercise101:
	gcc -Wall exercise101/hello.c
	./a.out
