.PHONY: exercise107
exercise107:
	gcc exercise107/copyChars.c
	cat exercise107/exercise107.testfile.txt | ./a.out

.PHONY: exercise106
exercise106:
	gcc exercise106/copyChars.c
	cat exercise106/exercise106.testfile.txt | ./a.out

.PHONY: exercise105
exercise105:
	gcc exercise105/tempConvert.c
	./a.out

.PHONY: exercise104
exercise104:
	gcc exercise104/tempConvert.c
	./a.out

.PHONY: exercise103
exercise103:
	gcc exercise103/tempConvert.c
	./a.out

.PHONY: exercise102
exercise102:
	gcc exercise102/hello.c
	./a.out

.PHONY: exercise101
exercise101:
	gcc -Wall exercise101/hello.c
	./a.out
