.PHONY: exercise504
exercise504:
	gcc -Wall -o exercise504/strend exercise504/strend.c
	exercise504/strend

.PHONY: exercise503
exercise503:
	gcc -Wall -o exercise503/strcat exercise503/strcat.c
	exercise503/strcat
